### PR TITLE
CI for Node

### PR DESCRIPTION
**Pull request by tasb**

### CODE REVIEW

**Comment by tasb** [comment]
Contains the compiled JavaScript
Initializes with two players
Starts the game with a random player
Sets the current player to be whoever it is not

**Comment by tasb** [comment]
Already merged!

**Comment by brianamarie** [comment]
Hi @tasb! I saw your message in the community forum. I'm not sure why the course got stuck, but I've manually moved you on to the next step. Here are the instructions that the bot would have posted. You should be on track to finish the course from here, but if you have any other problems, please let me know. You can find the instructions for your next step in #4.

**Comment by tasb** [comment]
Thanks @brianamarie! I can move on right now. I'll let you know if I've any issue.

**Comment by tasb** [comment]
Hi @brianamarie sorry to bother you again but I think that everytime that I finish a PR the new one (issue or PR) are not created so I cannot proceed.

**Pull request merged**
